use meta_signal_lojix::{
    META_LOJIX_INTERFACE_RUST, META_LOJIX_INTERFACE_SOURCE, bootstrap_manifest,
};

#[test]
fn canonical_source_imports_the_producer_and_keeps_roles_empty() {
    assert!(META_LOJIX_INTERFACE_SOURCE.starts_with("Interface.{1 0 0}\n[signal_lojix:lib.["));
    assert!(META_LOJIX_INTERFACE_SOURCE.contains("OwnerRequest.["));
    assert!(META_LOJIX_INTERFACE_SOURCE.contains("OwnerReply.["));
    assert!(META_LOJIX_INTERFACE_SOURCE.contains("\n  []\n  []\n  []\n  ["));
    assert!(!META_LOJIX_INTERFACE_SOURCE.contains("Optional."));
}

#[test]
fn strict_rust_projection_uses_encoded_local_and_imported_coordinates() {
    assert!(META_LOJIX_INTERFACE_RUST.starts_with(
        "// @generated by schema-rust from an authority-verified bootstrap Interface\n\n"
    ));
    for visible in ["OwnerRequest", "OwnerReply", "PinRequest"] {
        assert!(!META_LOJIX_INTERFACE_RUST.contains(&format!("pub enum {visible}")));
        assert!(!META_LOJIX_INTERFACE_RUST.contains(&format!("pub struct {visible}")));
    }
    assert!(META_LOJIX_INTERFACE_RUST.contains("signal_lojix::schema::lib::z"));
    assert!(bootstrap_manifest::DECLARATION_SEATS.len() > 80);
}
