// @generated by schema-rust from an authority-verified bootstrap Interface

pub struct z2VVxs ( z2VYoc ,) ;
pub struct z2VSqt {
    pub field_0: signal_lojix::schema::lib::z2VXtV,
    pub field_1: signal_lojix::schema::lib::z2VXGN,
    pub field_2: signal_lojix::schema::lib::z2VXcT,
    pub field_3: signal_lojix::schema::lib::z2VYbZ,
    pub field_4: signal_lojix::schema::lib::z2VXKF,
    pub field_5: signal_lojix::schema::lib::z2VSn8,
    pub field_6: signal_lojix::schema::lib::z2VQgC,
    pub field_7: signal_lojix::schema::lib::z2VXma,
    pub field_8: signal_lojix::schema::lib::z2VWva,
    pub field_9: signal_lojix::schema::lib::z2VbPz,
    pub field_10: signal_lojix::schema::lib::z2VLic,
    pub field_11: Option<signal_lojix::schema::lib::z2VatQ>,
    pub field_12: Vec<z2Vf5Q>,
}
pub struct z2VXPp {
    pub field_0: signal_lojix::schema::lib::z2VXtV,
    pub field_1: signal_lojix::schema::lib::z2VXGN,
    pub field_2: signal_lojix::schema::lib::z2VU8v,
    pub field_3: signal_lojix::schema::lib::z2VYbZ,
    pub field_4: signal_lojix::schema::lib::z2VXKF,
    pub field_5: signal_lojix::schema::lib::z2VSn8,
    pub field_6: signal_lojix::schema::lib::z2VQgC,
    pub field_7: signal_lojix::schema::lib::z2VXma,
    pub field_8: signal_lojix::schema::lib::z2VWva,
    pub field_9: signal_lojix::schema::lib::z2VZH3,
    pub field_10: signal_lojix::schema::lib::z2VLic,
    pub field_11: Option<signal_lojix::schema::lib::z2VatQ>,
    pub field_12: Vec<z2Vf5Q>,
}
pub struct z2VWgw {
    pub field_0: signal_lojix::schema::lib::z2VU8F,
    pub field_1: signal_lojix::schema::lib::z2VMFV,
    pub field_2: signal_lojix::schema::lib::z2VVKC,
    pub field_3: signal_lojix::schema::lib::z2VVKC,
    pub field_4: signal_lojix::schema::lib::z2VaUx,
}
pub enum z2Vdjb {z2VX44 , z2VdpR , z2VUC7 , z2VbwW , z2Vb8N ,} 
pub enum z2VQf9 {
    z2VbPt,
    z2VSB4(Vec<signal_lojix::schema::lib::z2VXGN>),
}
pub enum z2VQTA {z2VcHt , z2VcK6 , z2VXoJ , z2VVFQ , z2VWNx ,} 
pub struct z2VYoc {
    pub field_0: z2VYMd,
    pub field_1: signal_lojix::schema::lib::z2VaUx,
}
pub struct z2VeyT ( z2VaWL ,) ;
pub struct z2VToC ( z2Vd13 ,) ;
pub struct z2VNX9 ( z2VbsY ,) ;
pub struct z2Vd1z {
    pub field_0: signal_lojix::schema::lib::z2Vbti,
}
pub struct z2VSkE ( z2VWgw ,) ;
pub enum z2VLb3 {z2VeB5 , z2VU6C , z2VMap , z2VXpt ,} 
pub struct z2VagP(signal_lojix::schema::lib::z2Vbti);
impl z2VagP {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: signal_lojix::schema::lib::z2Vbti) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &signal_lojix::schema::lib::z2Vbti {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> signal_lojix::schema::lib::z2Vbti {
        self.0
    }
}
pub struct z2VXPq ( z2VRNK ,) ;
pub struct z2VLhK ( z2VdJT ,) ;
pub struct z2VdJT {
    pub field_0: signal_lojix::schema::lib::z2VXtV,
    pub field_1: signal_lojix::schema::lib::z2VXGN,
    pub field_2: signal_lojix::schema::lib::z2VU8F,
    pub field_3: signal_lojix::schema::lib::z2VMFV,
}
pub struct z2VNC3 {
    pub field_0: z2VLb3,
    pub field_1: signal_lojix::schema::lib::z2VaUx,
}
pub enum z2VbsY {z2VVnZ ( z2VUZQ ,) , z2VacZ ( z2VV26 ,) ,} 
pub struct z2VaWL {
    pub field_0: z2Vdjb,
    pub field_1: signal_lojix::schema::lib::z2VaUx,
}
pub struct z2VL1i {
    pub field_0: signal_lojix::schema::lib::z2VXtV,
    pub field_1: signal_lojix::schema::lib::z2VXGN,
    pub field_2: signal_lojix::schema::lib::z2VMFV,
}
pub struct z2VVa3 ( z2VLcY ,) ;
pub struct z2Vf5Q {
    pub field_0: std::string::String,
    pub field_1: std::string::String,
}
pub enum z2VeCY {z2VXfM ( z2VeyT ,) , z2VVNP ( z2VNJ9 ,) , z2VZGL ( z2VaSW ,) , z2VLs4 ( z2VVxs ,) , z2VU4f ( z2VToC ,) , z2VXfT ( z2VU7x ,) , z2VViz ( z2VTwF ,) , z2VUkZ ( z2VagP ,) , z2VTEY ( z2VSkE ,) , z2VZQK ( z2VdVE ,) , z2VShF ( z2VVa3 ,) ,} 
pub struct z2Vay1 ( z2VRo3 ,) ;
pub struct z2VSC9 ( z2VL1i ,) ;
pub struct z2VU7x ( z2VNWG ,) ;
pub struct z2VX4m {
    pub field_0: signal_lojix::schema::lib::z2Vdkm,
    pub field_1: signal_lojix::schema::lib::z2VaUx,
}
pub struct z2VRNK {
    pub field_0: signal_lojix::schema::lib::z2VXtV,
    pub field_1: signal_lojix::schema::lib::z2VXGN,
    pub field_2: signal_lojix::schema::lib::z2VU8F,
}
pub struct z2VTwF ( z2VNC3 ,) ;
pub enum z2VRo3 {z2VWv3 ( z2VSqt ,) , z2VMWS ( z2VXPp ,) ,} 
pub struct z2VV26(Vec<signal_lojix::schema::lib::z2VXGN>);
impl z2VV26 {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: Vec<signal_lojix::schema::lib::z2VXGN>) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &Vec<signal_lojix::schema::lib::z2VXGN> {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> Vec<signal_lojix::schema::lib::z2VXGN> {
        self.0
    }
}
pub struct z2VdVE ( z2VdjM ,) ;
pub struct z2VNWG {
    pub field_0: signal_lojix::schema::lib::z2VNzL,
    pub field_1: signal_lojix::schema::lib::z2VaUx,
}
pub struct z2Vd13 {
    pub field_0: signal_lojix::schema::lib::z2VU8F,
    pub field_1: signal_lojix::schema::lib::z2VMFV,
    pub field_2: signal_lojix::schema::lib::z2VVKC,
    pub field_3: signal_lojix::schema::lib::z2VVKC,
    pub field_4: signal_lojix::schema::lib::z2VaUx,
}
pub enum z2VYMd {z2VV5m , z2VLeY , z2Vb51 , z2VLRJ , z2VP1k , z2Veut , z2Vavq , z2VKyX ,} 
pub struct z2VdjM {
    pub field_0: z2VQTA,
    pub field_1: signal_lojix::schema::lib::z2VaUx,
}
pub enum z2VW7Q {z2VM8s ( z2VXPq ,) , z2VevS ( z2VLhK ,) , z2VXB8 ( z2Vay1 ,) , z2VMJW ( z2VNX9 ,) , z2Vc5o ( z2VSC9 ,) ,} 
pub struct z2VaSW ( z2VX4m ,) ;
pub struct z2VLcY {
    pub field_0: signal_lojix::schema::lib::z2VU8F,
    pub field_1: signal_lojix::schema::lib::z2VVKC,
    pub field_2: signal_lojix::schema::lib::z2VaUx,
}
pub struct z2VUZQ {
    pub field_0: signal_lojix::schema::lib::z2VXtV,
    pub field_1: z2VQf9,
    pub field_2: signal_lojix::schema::lib::z2Vbmn,
    pub field_3: signal_lojix::schema::lib::z2VL3w,
}
pub struct z2VNJ9 ( z2Vd1z ,) ;
