// @generated by schema-rust-next

pub type String = std::string::String;
pub type Integer = u64;
pub type Boolean = bool;
pub type Path = std::string::String;

pub use signal_lojix::schema::lib::DeploymentIdentifier as DeploymentIdentifier;
pub use signal_lojix::schema::lib::GenerationIdentifier as GenerationIdentifier;
pub use signal_lojix::schema::lib::ClusterName as ClusterName;
pub use signal_lojix::schema::lib::NodeName as NodeName;
pub use signal_lojix::schema::lib::UserName as UserName;
pub use signal_lojix::schema::lib::PinLabel as PinLabel;
pub use signal_lojix::schema::lib::DeploymentKind as DeploymentKind;
pub use signal_lojix::schema::lib::SystemAction as SystemAction;
pub use signal_lojix::schema::lib::GenerationSlot as GenerationSlot;
pub use signal_lojix::schema::lib::ProposalSource as ProposalSource;
pub use signal_lojix::schema::lib::FlakeReference as FlakeReference;
pub use signal_lojix::schema::lib::DatabaseMarker as DatabaseMarker;

#[cfg(feature = "nota-text")]
pub use nota_next::{
    NotaDecode, NotaDecodeError, NotaEncode, NotaSource,
};

pub type Deploy = DeployRequest;

pub type Pin = PinRequest;

pub type Unpin = UnpinRequest;

pub type Retire = RetireRequest;

pub type Deployed = AcceptedDeploy;

pub type DeployRejected = RejectedDeploy;

pub type Pinned = AppliedPin;

pub type PinRejected = RejectedPin;

pub type Unpinned = AppliedUnpin;

pub type UnpinRejected = RejectedUnpin;

pub type Retired = AppliedRetire;

pub type RetireRejected = RejectedRetire;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum HomeMode {
    Build,
    Profile,
    Activate,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ExtraSubstituter {
    pub url: String,
    pub public_key: String,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Builder(pub NodeName);

pub type FlakeAttribute = String;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SystemDeployment {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub deployment_kind: DeploymentKind,
    pub source: ProposalSource,
    pub flake: FlakeReference,
    pub system_action: SystemAction,
    pub builder: Option<Builder>,
    pub substituters: Vec<ExtraSubstituter>,
    pub build_attribute: Option<FlakeAttribute>,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct HomeDeployment {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub user_name: UserName,
    pub source: ProposalSource,
    pub flake: FlakeReference,
    pub home_mode: HomeMode,
    pub builder: Option<Builder>,
    pub substituters: Vec<ExtraSubstituter>,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum DeployRequest {
    System(SystemDeployment),
    Home(HomeDeployment),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PinRequest {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub generation_identifier: GenerationIdentifier,
    pub pin_label: PinLabel,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UnpinRequest {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub pin_label: PinLabel,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RetireRequest {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub generation_identifier: GenerationIdentifier,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AcceptedDeploy {
    pub deployment_identifier: DeploymentIdentifier,
    pub database_marker: DatabaseMarker,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AppliedPin {
    pub generation_identifier: GenerationIdentifier,
    pub pin_label: PinLabel,
    pub from_slot: GenerationSlot,
    pub to_slot: GenerationSlot,
    pub database_marker: DatabaseMarker,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AppliedUnpin {
    pub generation_identifier: GenerationIdentifier,
    pub pin_label: PinLabel,
    pub from_slot: GenerationSlot,
    pub to_slot: GenerationSlot,
    pub database_marker: DatabaseMarker,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AppliedRetire {
    pub generation_identifier: GenerationIdentifier,
    pub from_slot: GenerationSlot,
    pub database_marker: DatabaseMarker,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum DeployRejectionReason {
    ClusterUnknown,
    NodeUnknown,
    ProposalSourceUnreachable,
    FlakeReferenceMalformed,
    BuilderUnreachable,
    SubstituterUnreachable,
    DeploymentInFlight,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum PinRejectionReason {
    GenerationUnknown,
    NodeUnknown,
    PinLabelInUse,
    PinSlotExhausted,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum UnpinRejectionReason {
    PinLabelUnknown,
    NodeUnknown,
    GenerationNotPinned,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum RetireRejectionReason {
    GenerationUnknown,
    NodeUnknown,
    GenerationActive,
    GenerationPinned,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectedDeploy {
    pub deploy_rejection_reason: DeployRejectionReason,
    pub database_marker: DatabaseMarker,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectedPin {
    pub pin_rejection_reason: PinRejectionReason,
    pub database_marker: DatabaseMarker,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectedUnpin {
    pub unpin_rejection_reason: UnpinRejectionReason,
    pub database_marker: DatabaseMarker,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectedRetire {
    pub retire_rejection_reason: RetireRejectionReason,
    pub database_marker: DatabaseMarker,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Deploy(Deploy),
    Pin(Pin),
    Unpin(Unpin),
    Retire(Retire),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    Deployed(Deployed),
    DeployRejected(DeployRejected),
    Pinned(Pinned),
    PinRejected(PinRejected),
    Unpinned(Unpinned),
    UnpinRejected(UnpinRejected),
    Retired(Retired),
    RetireRejected(RetireRejected),
}

impl Builder {
    pub fn new(payload: NodeName) -> Self {
        Self(payload)
    }

    pub fn payload(&self) -> &NodeName {
        &self.0
    }

    pub fn into_payload(self) -> NodeName {
        self.0
    }
}

impl From<NodeName> for Builder {
    fn from(payload: NodeName) -> Self {
        Self::new(payload)
    }
}

impl DeployRequest {
    pub fn system(payload: SystemDeployment) -> Self {
        Self::System(payload)
    }

    pub fn home(payload: HomeDeployment) -> Self {
        Self::Home(payload)
    }
}

impl Input {
    pub fn deploy(payload: Deploy) -> Self {
        Self::Deploy(payload)
    }

    pub fn pin(payload: Pin) -> Self {
        Self::Pin(payload)
    }

    pub fn unpin(payload: Unpin) -> Self {
        Self::Unpin(payload)
    }

    pub fn retire(payload: Retire) -> Self {
        Self::Retire(payload)
    }
}

impl Output {
    pub fn deployed(payload: Deployed) -> Self {
        Self::Deployed(payload)
    }

    pub fn deploy_rejected(payload: DeployRejected) -> Self {
        Self::DeployRejected(payload)
    }

    pub fn pinned(payload: Pinned) -> Self {
        Self::Pinned(payload)
    }

    pub fn pin_rejected(payload: PinRejected) -> Self {
        Self::PinRejected(payload)
    }

    pub fn unpinned(payload: Unpinned) -> Self {
        Self::Unpinned(payload)
    }

    pub fn unpin_rejected(payload: UnpinRejected) -> Self {
        Self::UnpinRejected(payload)
    }

    pub fn retired(payload: Retired) -> Self {
        Self::Retired(payload)
    }

    pub fn retire_rejected(payload: RetireRejected) -> Self {
        Self::RetireRejected(payload)
    }
}

impl From<SystemDeployment> for DeployRequest {
    fn from(payload: SystemDeployment) -> Self {
        Self::System(payload)
    }
}

impl From<HomeDeployment> for DeployRequest {
    fn from(payload: HomeDeployment) -> Self {
        Self::Home(payload)
    }
}

#[cfg(feature = "nota-text")]
impl HomeMode {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ExtraSubstituter {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Builder {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl SystemDeployment {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl HomeDeployment {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl DeployRequest {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl PinRequest {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl UnpinRequest {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RetireRequest {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl AcceptedDeploy {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl AppliedPin {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl AppliedUnpin {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl AppliedRetire {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl DeployRejectionReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl PinRejectionReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl UnpinRejectionReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RetireRejectionReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RejectedDeploy {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RejectedPin {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RejectedUnpin {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RejectedRetire {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Input {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;

    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}

#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[cfg(feature = "nota-text")]
impl Output {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;

    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}

#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

pub mod short_header {
    pub const INPUT_DEPLOY: u64 = 0x0000000000000000;
    pub const INPUT_PIN: u64 = 0x0001000000000000;
    pub const INPUT_UNPIN: u64 = 0x0002000000000000;
    pub const INPUT_RETIRE: u64 = 0x0003000000000000;
    pub const OUTPUT_DEPLOYED: u64 = 0x0100000000000000;
    pub const OUTPUT_DEPLOY_REJECTED: u64 = 0x0101000000000000;
    pub const OUTPUT_PINNED: u64 = 0x0102000000000000;
    pub const OUTPUT_PIN_REJECTED: u64 = 0x0103000000000000;
    pub const OUTPUT_UNPINNED: u64 = 0x0104000000000000;
    pub const OUTPUT_UNPIN_REJECTED: u64 = 0x0105000000000000;
    pub const OUTPUT_RETIRED: u64 = 0x0106000000000000;
    pub const OUTPUT_RETIRE_REJECTED: u64 = 0x0107000000000000;
}

const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}

impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => write!(formatter, "signal frame too short: {found} bytes"),
            Self::UnknownHeader { root_enum, header } => write!(formatter, "unknown {root_enum} short header 0x{header:016X}"),
            Self::HeaderMismatch { expected, found } => write!(formatter, "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"),
        }
    }
}

impl std::error::Error for SignalFrameError {}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum InputRoute {
    Deploy,
    Pin,
    Unpin,
    Retire,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub enum OutputRoute {
    Deployed,
    DeployRejected,
    Pinned,
    PinRejected,
    Unpinned,
    UnpinRejected,
    Retired,
    RetireRejected,
}

impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Deploy(_) => InputRoute::Deploy,
            Self::Pin(_) => InputRoute::Pin,
            Self::Unpin(_) => InputRoute::Unpin,
            Self::Retire(_) => InputRoute::Retire,
        }
    }

    pub fn short_header(&self) -> u64 {
        match self {
            Self::Deploy(_) => short_header::INPUT_DEPLOY,
            Self::Pin(_) => short_header::INPUT_PIN,
            Self::Unpin(_) => short_header::INPUT_UNPIN,
            Self::Retire(_) => short_header::INPUT_RETIRE,
        }
    }

    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_DEPLOY => Ok(InputRoute::Deploy),
            short_header::INPUT_PIN => Ok(InputRoute::Pin),
            short_header::INPUT_UNPIN => Ok(InputRoute::Unpin),
            short_header::INPUT_RETIRE => Ok(InputRoute::Retire),
            _ => Err(SignalFrameError::UnknownHeader { root_enum: "Input", header }),
        }
    }

    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len());
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }

    pub fn decode_signal_frame(frame: &[u8]) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort { found: frame.len() });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<Self, rkyv::rancor::Error>(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch { expected, found: header });
        }
        Ok((route, value))
    }
}

impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::Deployed(_) => OutputRoute::Deployed,
            Self::DeployRejected(_) => OutputRoute::DeployRejected,
            Self::Pinned(_) => OutputRoute::Pinned,
            Self::PinRejected(_) => OutputRoute::PinRejected,
            Self::Unpinned(_) => OutputRoute::Unpinned,
            Self::UnpinRejected(_) => OutputRoute::UnpinRejected,
            Self::Retired(_) => OutputRoute::Retired,
            Self::RetireRejected(_) => OutputRoute::RetireRejected,
        }
    }

    pub fn short_header(&self) -> u64 {
        match self {
            Self::Deployed(_) => short_header::OUTPUT_DEPLOYED,
            Self::DeployRejected(_) => short_header::OUTPUT_DEPLOY_REJECTED,
            Self::Pinned(_) => short_header::OUTPUT_PINNED,
            Self::PinRejected(_) => short_header::OUTPUT_PIN_REJECTED,
            Self::Unpinned(_) => short_header::OUTPUT_UNPINNED,
            Self::UnpinRejected(_) => short_header::OUTPUT_UNPIN_REJECTED,
            Self::Retired(_) => short_header::OUTPUT_RETIRED,
            Self::RetireRejected(_) => short_header::OUTPUT_RETIRE_REJECTED,
        }
    }

    pub fn route_from_short_header(header: u64) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_DEPLOYED => Ok(OutputRoute::Deployed),
            short_header::OUTPUT_DEPLOY_REJECTED => Ok(OutputRoute::DeployRejected),
            short_header::OUTPUT_PINNED => Ok(OutputRoute::Pinned),
            short_header::OUTPUT_PIN_REJECTED => Ok(OutputRoute::PinRejected),
            short_header::OUTPUT_UNPINNED => Ok(OutputRoute::Unpinned),
            short_header::OUTPUT_UNPIN_REJECTED => Ok(OutputRoute::UnpinRejected),
            short_header::OUTPUT_RETIRED => Ok(OutputRoute::Retired),
            short_header::OUTPUT_RETIRE_REJECTED => Ok(OutputRoute::RetireRejected),
            _ => Err(SignalFrameError::UnknownHeader { root_enum: "Output", header }),
        }
    }

    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len());
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }

    pub fn decode_signal_frame(frame: &[u8]) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort { found: frame.len() });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<Self, rkyv::rancor::Error>(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch { expected, found: header });
        }
        Ok((route, value))
    }
}

