// @generated by schema-rust

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
pub use signal_lojix::schema::lib::DeploymentIdentifier as DeploymentIdentifier;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::GenerationIdentifier as GenerationIdentifier;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::TestRunIdentifier as TestRunIdentifier;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::ClusterName as ClusterName;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::NodeName as NodeName;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::UserName as UserName;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::PinLabel as PinLabel;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::HostComposition as HostComposition;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::HostDeployAction as HostDeployAction;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::UserEnvironmentAction as UserEnvironmentAction;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::SourceRevisionPolicy as SourceRevisionPolicy;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::GenerationSlot as GenerationSlot;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::ProposalSource as ProposalSource;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::FlakeReference as FlakeReference;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::DatabaseMarker as DatabaseMarker;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::TestMode as TestMode;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::HostSelection as HostSelection;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeployPayload(DeployRequest);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PinPayload(PinRequest);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UnpinPayload(UnpinRequest);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RetirePayload(RetireRequest);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TestPayload(TestRequest);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeployAcceptedPayload(DeployHandle);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeployRejectedPayload(RejectedDeploy);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PinnedPayload(AppliedPin);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PinRejectedPayload(RejectedPin);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UnpinnedPayload(AppliedUnpin);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UnpinRejectedPayload(RejectedUnpin);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RetiredPayload(AppliedRetire);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RetireRejectedPayload(RejectedRetire);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TestedPayload(AcceptedTest);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TestRejectedPayload(RejectedTest);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum TestRequest {
    Run(TestRun),
    Check(QuickCheck),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NodeSelection {
    Nodes(Vec<NodeName>),
    All,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TestRun {
    pub cluster_name: ClusterName,
    pub node_selection: NodeSelection,
    pub host_selection: HostSelection,
    pub test_mode: TestMode,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct QuickCheck(Vec<NodeName>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ExtraSubstituter {
    pub url: String,
    pub public_key: String,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Builder(NodeName);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct FlakeAttribute(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct HostDeployment {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub host_composition: HostComposition,
    pub proposal_source: ProposalSource,
    pub flake_reference: FlakeReference,
    pub host_deploy_action: HostDeployAction,
    pub source_revision_policy: SourceRevisionPolicy,
    pub optional_builder: Option<Builder>,
    pub extra_substituter_vector: Vec<ExtraSubstituter>,
    pub optional_flake_attribute: Option<FlakeAttribute>,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UserEnvironmentDeployment {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub user_name: UserName,
    pub proposal_source: ProposalSource,
    pub flake_reference: FlakeReference,
    pub user_environment_action: UserEnvironmentAction,
    pub source_revision_policy: SourceRevisionPolicy,
    pub optional_builder: Option<Builder>,
    pub extra_substituter_vector: Vec<ExtraSubstituter>,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum DeployRequest {
    Host(HostDeployment),
    UserEnvironment(UserEnvironmentDeployment),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PinRequest {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub generation_identifier: GenerationIdentifier,
    pub pin_label: PinLabel,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UnpinRequest {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub pin_label: PinLabel,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RetireRequest {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub generation_identifier: GenerationIdentifier,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeployHandle {
    pub deployment_identifier: DeploymentIdentifier,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AcceptedTest {
    pub test_run_identifier: TestRunIdentifier,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AppliedPin {
    pub generation_identifier: GenerationIdentifier,
    pub pin_label: PinLabel,
    pub from_slot: GenerationSlot,
    pub to_slot: GenerationSlot,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AppliedUnpin {
    pub generation_identifier: GenerationIdentifier,
    pub pin_label: PinLabel,
    pub from_slot: GenerationSlot,
    pub to_slot: GenerationSlot,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AppliedRetire {
    pub generation_identifier: GenerationIdentifier,
    pub generation_slot: GenerationSlot,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum DeployRejectionReason {
    ClusterUnknown,
    NodeUnknown,
    ProposalSourceUnreachable,
    FlakeReferenceMalformed,
    BuilderUnreachable,
    SubstituterUnreachable,
    DeploymentInFlight,
    UnsupportedDeployAction,
    InternalError,
    ActivationFailed,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum PinRejectionReason {
    GenerationUnknown,
    NodeUnknown,
    PinLabelInUse,
    PinSlotExhausted,
    InternalError,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum UnpinRejectionReason {
    PinLabelUnknown,
    NodeUnknown,
    GenerationNotPinned,
    InternalError,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum RetireRejectionReason {
    GenerationUnknown,
    NodeUnknown,
    GenerationActive,
    GenerationPinned,
    InternalError,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum TestRejectionReason {
    ClusterUnknown,
    NodeUnknown,
    VmHostNotDeclaredForNode,
    HostDeclaresNoVmHost,
    NoTestDefaults,
    LiveNotYetEnabled,
    SubstrateUnavailable,
    InternalError,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectedDeploy {
    pub deploy_rejection_reason: DeployRejectionReason,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectedPin {
    pub pin_rejection_reason: PinRejectionReason,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectedUnpin {
    pub unpin_rejection_reason: UnpinRejectionReason,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectedRetire {
    pub retire_rejection_reason: RetireRejectionReason,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectedTest {
    pub test_rejection_reason: TestRejectionReason,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Deploy(DeployPayload),
    Pin(PinPayload),
    Unpin(UnpinPayload),
    Retire(RetirePayload),
    Test(TestPayload),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    DeployAccepted(DeployAcceptedPayload),
    DeployRejected(DeployRejectedPayload),
    Pinned(PinnedPayload),
    PinRejected(PinRejectedPayload),
    Unpinned(UnpinnedPayload),
    UnpinRejected(UnpinRejectedPayload),
    Retired(RetiredPayload),
    RetireRejected(RetireRejectedPayload),
    Tested(TestedPayload),
    TestRejected(TestRejectedPayload),
}

#[rustfmt::skip]
impl DeployPayload {
    pub fn new(payload: DeployRequest) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &DeployRequest {
        &self.0
    }
    pub fn into_payload(self) -> DeployRequest {
        self.0
    }
}
#[rustfmt::skip]
impl From<DeployRequest> for DeployPayload {
    fn from(payload: DeployRequest) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PinPayload {
    pub fn new(payload: PinRequest) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &PinRequest {
        &self.0
    }
    pub fn into_payload(self) -> PinRequest {
        self.0
    }
}
#[rustfmt::skip]
impl From<PinRequest> for PinPayload {
    fn from(payload: PinRequest) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl UnpinPayload {
    pub fn new(payload: UnpinRequest) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &UnpinRequest {
        &self.0
    }
    pub fn into_payload(self) -> UnpinRequest {
        self.0
    }
}
#[rustfmt::skip]
impl From<UnpinRequest> for UnpinPayload {
    fn from(payload: UnpinRequest) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RetirePayload {
    pub fn new(payload: RetireRequest) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RetireRequest {
        &self.0
    }
    pub fn into_payload(self) -> RetireRequest {
        self.0
    }
}
#[rustfmt::skip]
impl From<RetireRequest> for RetirePayload {
    fn from(payload: RetireRequest) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TestPayload {
    pub fn new(payload: TestRequest) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &TestRequest {
        &self.0
    }
    pub fn into_payload(self) -> TestRequest {
        self.0
    }
}
#[rustfmt::skip]
impl From<TestRequest> for TestPayload {
    fn from(payload: TestRequest) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DeployAcceptedPayload {
    pub fn new(payload: DeployHandle) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &DeployHandle {
        &self.0
    }
    pub fn into_payload(self) -> DeployHandle {
        self.0
    }
}
#[rustfmt::skip]
impl From<DeployHandle> for DeployAcceptedPayload {
    fn from(payload: DeployHandle) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DeployRejectedPayload {
    pub fn new(payload: RejectedDeploy) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RejectedDeploy {
        &self.0
    }
    pub fn into_payload(self) -> RejectedDeploy {
        self.0
    }
}
#[rustfmt::skip]
impl From<RejectedDeploy> for DeployRejectedPayload {
    fn from(payload: RejectedDeploy) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PinnedPayload {
    pub fn new(payload: AppliedPin) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &AppliedPin {
        &self.0
    }
    pub fn into_payload(self) -> AppliedPin {
        self.0
    }
}
#[rustfmt::skip]
impl From<AppliedPin> for PinnedPayload {
    fn from(payload: AppliedPin) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PinRejectedPayload {
    pub fn new(payload: RejectedPin) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RejectedPin {
        &self.0
    }
    pub fn into_payload(self) -> RejectedPin {
        self.0
    }
}
#[rustfmt::skip]
impl From<RejectedPin> for PinRejectedPayload {
    fn from(payload: RejectedPin) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl UnpinnedPayload {
    pub fn new(payload: AppliedUnpin) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &AppliedUnpin {
        &self.0
    }
    pub fn into_payload(self) -> AppliedUnpin {
        self.0
    }
}
#[rustfmt::skip]
impl From<AppliedUnpin> for UnpinnedPayload {
    fn from(payload: AppliedUnpin) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl UnpinRejectedPayload {
    pub fn new(payload: RejectedUnpin) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RejectedUnpin {
        &self.0
    }
    pub fn into_payload(self) -> RejectedUnpin {
        self.0
    }
}
#[rustfmt::skip]
impl From<RejectedUnpin> for UnpinRejectedPayload {
    fn from(payload: RejectedUnpin) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RetiredPayload {
    pub fn new(payload: AppliedRetire) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &AppliedRetire {
        &self.0
    }
    pub fn into_payload(self) -> AppliedRetire {
        self.0
    }
}
#[rustfmt::skip]
impl From<AppliedRetire> for RetiredPayload {
    fn from(payload: AppliedRetire) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RetireRejectedPayload {
    pub fn new(payload: RejectedRetire) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RejectedRetire {
        &self.0
    }
    pub fn into_payload(self) -> RejectedRetire {
        self.0
    }
}
#[rustfmt::skip]
impl From<RejectedRetire> for RetireRejectedPayload {
    fn from(payload: RejectedRetire) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TestedPayload {
    pub fn new(payload: AcceptedTest) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &AcceptedTest {
        &self.0
    }
    pub fn into_payload(self) -> AcceptedTest {
        self.0
    }
}
#[rustfmt::skip]
impl From<AcceptedTest> for TestedPayload {
    fn from(payload: AcceptedTest) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TestRejectedPayload {
    pub fn new(payload: RejectedTest) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RejectedTest {
        &self.0
    }
    pub fn into_payload(self) -> RejectedTest {
        self.0
    }
}
#[rustfmt::skip]
impl From<RejectedTest> for TestRejectedPayload {
    fn from(payload: RejectedTest) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl QuickCheck {
    pub fn new(payload: Vec<NodeName>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<NodeName> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<NodeName> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<NodeName>> for QuickCheck {
    fn from(payload: Vec<NodeName>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Builder {
    pub fn new(payload: NodeName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &NodeName {
        &self.0
    }
    pub fn into_payload(self) -> NodeName {
        self.0
    }
}
#[rustfmt::skip]
impl From<NodeName> for Builder {
    fn from(payload: NodeName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl FlakeAttribute {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for FlakeAttribute {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TestRequest {
    pub fn run(payload: TestRun) -> Self {
        Self::Run(payload)
    }
    pub fn check(payload: Vec<NodeName>) -> Self {
        Self::Check(QuickCheck::new(payload))
    }
}

#[rustfmt::skip]
impl NodeSelection {
    pub fn nodes(payload: Vec<NodeName>) -> Self {
        Self::Nodes(payload)
    }
}

#[rustfmt::skip]
impl DeployRequest {
    pub fn host(payload: HostDeployment) -> Self {
        Self::Host(payload)
    }
    pub fn user_environment(payload: UserEnvironmentDeployment) -> Self {
        Self::UserEnvironment(payload)
    }
}

#[rustfmt::skip]
impl Input {
    pub fn deploy(payload: DeployRequest) -> Self {
        Self::Deploy(DeployPayload::new(payload))
    }
    pub fn pin(payload: PinRequest) -> Self {
        Self::Pin(PinPayload::new(payload))
    }
    pub fn unpin(payload: UnpinRequest) -> Self {
        Self::Unpin(UnpinPayload::new(payload))
    }
    pub fn retire(payload: RetireRequest) -> Self {
        Self::Retire(RetirePayload::new(payload))
    }
    pub fn test(payload: TestRequest) -> Self {
        Self::Test(TestPayload::new(payload))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn deploy_accepted(payload: DeployHandle) -> Self {
        Self::DeployAccepted(DeployAcceptedPayload::new(payload))
    }
    pub fn deploy_rejected(payload: RejectedDeploy) -> Self {
        Self::DeployRejected(DeployRejectedPayload::new(payload))
    }
    pub fn pinned(payload: AppliedPin) -> Self {
        Self::Pinned(PinnedPayload::new(payload))
    }
    pub fn pin_rejected(payload: RejectedPin) -> Self {
        Self::PinRejected(PinRejectedPayload::new(payload))
    }
    pub fn unpinned(payload: AppliedUnpin) -> Self {
        Self::Unpinned(UnpinnedPayload::new(payload))
    }
    pub fn unpin_rejected(payload: RejectedUnpin) -> Self {
        Self::UnpinRejected(UnpinRejectedPayload::new(payload))
    }
    pub fn retired(payload: AppliedRetire) -> Self {
        Self::Retired(RetiredPayload::new(payload))
    }
    pub fn retire_rejected(payload: RejectedRetire) -> Self {
        Self::RetireRejected(RetireRejectedPayload::new(payload))
    }
    pub fn tested(payload: AcceptedTest) -> Self {
        Self::Tested(TestedPayload::new(payload))
    }
    pub fn test_rejected(payload: RejectedTest) -> Self {
        Self::TestRejected(TestRejectedPayload::new(payload))
    }
}

#[rustfmt::skip]
impl From<TestRun> for TestRequest {
    fn from(payload: TestRun) -> Self {
        Self::Run(payload)
    }
}

#[rustfmt::skip]
impl From<QuickCheck> for TestRequest {
    fn from(payload: QuickCheck) -> Self {
        Self::Check(payload)
    }
}

#[rustfmt::skip]
impl From<HostDeployment> for DeployRequest {
    fn from(payload: HostDeployment) -> Self {
        Self::Host(payload)
    }
}

#[rustfmt::skip]
impl From<UserEnvironmentDeployment> for DeployRequest {
    fn from(payload: UserEnvironmentDeployment) -> Self {
        Self::UserEnvironment(payload)
    }
}

#[rustfmt::skip]
impl From<DeployPayload> for Input {
    fn from(payload: DeployPayload) -> Self {
        Self::Deploy(payload)
    }
}

#[rustfmt::skip]
impl From<PinPayload> for Input {
    fn from(payload: PinPayload) -> Self {
        Self::Pin(payload)
    }
}

#[rustfmt::skip]
impl From<UnpinPayload> for Input {
    fn from(payload: UnpinPayload) -> Self {
        Self::Unpin(payload)
    }
}

#[rustfmt::skip]
impl From<RetirePayload> for Input {
    fn from(payload: RetirePayload) -> Self {
        Self::Retire(payload)
    }
}

#[rustfmt::skip]
impl From<TestPayload> for Input {
    fn from(payload: TestPayload) -> Self {
        Self::Test(payload)
    }
}

#[rustfmt::skip]
impl From<DeployAcceptedPayload> for Output {
    fn from(payload: DeployAcceptedPayload) -> Self {
        Self::DeployAccepted(payload)
    }
}

#[rustfmt::skip]
impl From<DeployRejectedPayload> for Output {
    fn from(payload: DeployRejectedPayload) -> Self {
        Self::DeployRejected(payload)
    }
}

#[rustfmt::skip]
impl From<PinnedPayload> for Output {
    fn from(payload: PinnedPayload) -> Self {
        Self::Pinned(payload)
    }
}

#[rustfmt::skip]
impl From<PinRejectedPayload> for Output {
    fn from(payload: PinRejectedPayload) -> Self {
        Self::PinRejected(payload)
    }
}

#[rustfmt::skip]
impl From<UnpinnedPayload> for Output {
    fn from(payload: UnpinnedPayload) -> Self {
        Self::Unpinned(payload)
    }
}

#[rustfmt::skip]
impl From<UnpinRejectedPayload> for Output {
    fn from(payload: UnpinRejectedPayload) -> Self {
        Self::UnpinRejected(payload)
    }
}

#[rustfmt::skip]
impl From<RetiredPayload> for Output {
    fn from(payload: RetiredPayload) -> Self {
        Self::Retired(payload)
    }
}

#[rustfmt::skip]
impl From<RetireRejectedPayload> for Output {
    fn from(payload: RetireRejectedPayload) -> Self {
        Self::RetireRejected(payload)
    }
}

#[rustfmt::skip]
impl From<TestedPayload> for Output {
    fn from(payload: TestedPayload) -> Self {
        Self::Tested(payload)
    }
}

#[rustfmt::skip]
impl From<TestRejectedPayload> for Output {
    fn from(payload: TestRejectedPayload) -> Self {
        Self::TestRejected(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_DEPLOY: u64 = 0x0000000000000000;
    pub const INPUT_PIN: u64 = 0x0001000000000000;
    pub const INPUT_UNPIN: u64 = 0x0002000000000000;
    pub const INPUT_RETIRE: u64 = 0x0003000000000000;
    pub const INPUT_TEST: u64 = 0x0004000000000000;
    pub const OUTPUT_DEPLOY_ACCEPTED: u64 = 0x0100000000000000;
    pub const OUTPUT_DEPLOY_REJECTED: u64 = 0x0101000000000000;
    pub const OUTPUT_PINNED: u64 = 0x0102000000000000;
    pub const OUTPUT_PIN_REJECTED: u64 = 0x0103000000000000;
    pub const OUTPUT_UNPINNED: u64 = 0x0104000000000000;
    pub const OUTPUT_UNPIN_REJECTED: u64 = 0x0105000000000000;
    pub const OUTPUT_RETIRED: u64 = 0x0106000000000000;
    pub const OUTPUT_RETIRE_REJECTED: u64 = 0x0107000000000000;
    pub const OUTPUT_TESTED: u64 = 0x0108000000000000;
    pub const OUTPUT_TEST_REJECTED: u64 = 0x0109000000000000;
}

#[rustfmt::skip]
const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::UnknownHeader { root_enum, header } => {
                write!(formatter, "unknown {root_enum} short header 0x{header:016X}")
            }
            Self::HeaderMismatch { expected, found } => {
                write!(
                    formatter,
                    "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"
                )
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    Deploy,
    Pin,
    Unpin,
    Retire,
    Test,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    DeployAccepted,
    DeployRejected,
    Pinned,
    PinRejected,
    Unpinned,
    UnpinRejected,
    Retired,
    RetireRejected,
    Tested,
    TestRejected,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Deploy(_) => InputRoute::Deploy,
            Self::Pin(_) => InputRoute::Pin,
            Self::Unpin(_) => InputRoute::Unpin,
            Self::Retire(_) => InputRoute::Retire,
            Self::Test(_) => InputRoute::Test,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Deploy(_) => short_header::INPUT_DEPLOY,
            Self::Pin(_) => short_header::INPUT_PIN,
            Self::Unpin(_) => short_header::INPUT_UNPIN,
            Self::Retire(_) => short_header::INPUT_RETIRE,
            Self::Test(_) => short_header::INPUT_TEST,
        }
    }
    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_DEPLOY => Ok(InputRoute::Deploy),
            short_header::INPUT_PIN => Ok(InputRoute::Pin),
            short_header::INPUT_UNPIN => Ok(InputRoute::Unpin),
            short_header::INPUT_RETIRE => Ok(InputRoute::Retire),
            short_header::INPUT_TEST => Ok(InputRoute::Test),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Input",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::DeployAccepted(_) => OutputRoute::DeployAccepted,
            Self::DeployRejected(_) => OutputRoute::DeployRejected,
            Self::Pinned(_) => OutputRoute::Pinned,
            Self::PinRejected(_) => OutputRoute::PinRejected,
            Self::Unpinned(_) => OutputRoute::Unpinned,
            Self::UnpinRejected(_) => OutputRoute::UnpinRejected,
            Self::Retired(_) => OutputRoute::Retired,
            Self::RetireRejected(_) => OutputRoute::RetireRejected,
            Self::Tested(_) => OutputRoute::Tested,
            Self::TestRejected(_) => OutputRoute::TestRejected,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::DeployAccepted(_) => short_header::OUTPUT_DEPLOY_ACCEPTED,
            Self::DeployRejected(_) => short_header::OUTPUT_DEPLOY_REJECTED,
            Self::Pinned(_) => short_header::OUTPUT_PINNED,
            Self::PinRejected(_) => short_header::OUTPUT_PIN_REJECTED,
            Self::Unpinned(_) => short_header::OUTPUT_UNPINNED,
            Self::UnpinRejected(_) => short_header::OUTPUT_UNPIN_REJECTED,
            Self::Retired(_) => short_header::OUTPUT_RETIRED,
            Self::RetireRejected(_) => short_header::OUTPUT_RETIRE_REJECTED,
            Self::Tested(_) => short_header::OUTPUT_TESTED,
            Self::TestRejected(_) => short_header::OUTPUT_TEST_REJECTED,
        }
    }
    pub fn route_from_short_header(
        header: u64,
    ) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_DEPLOY_ACCEPTED => Ok(OutputRoute::DeployAccepted),
            short_header::OUTPUT_DEPLOY_REJECTED => Ok(OutputRoute::DeployRejected),
            short_header::OUTPUT_PINNED => Ok(OutputRoute::Pinned),
            short_header::OUTPUT_PIN_REJECTED => Ok(OutputRoute::PinRejected),
            short_header::OUTPUT_UNPINNED => Ok(OutputRoute::Unpinned),
            short_header::OUTPUT_UNPIN_REJECTED => Ok(OutputRoute::UnpinRejected),
            short_header::OUTPUT_RETIRED => Ok(OutputRoute::Retired),
            short_header::OUTPUT_RETIRE_REJECTED => Ok(OutputRoute::RetireRejected),
            short_header::OUTPUT_TESTED => Ok(OutputRoute::Tested),
            short_header::OUTPUT_TEST_REJECTED => Ok(OutputRoute::TestRejected),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Output",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl signal_frame::RequestPayload for Input {}
#[rustfmt::skip]
impl signal_frame::SignalOperationHeads for Input {
    const HEADS: &'static [&'static str] = &["Deploy", "Pin", "Unpin", "Retire", "Test"];
}
#[rustfmt::skip]
impl signal_frame::LogVariant for Input {
    fn log_variant(&self) -> u64 {
        self.short_header()
    }
}
#[rustfmt::skip]
pub type Frame = signal_frame::ExchangeFrame<Input, Output>;
#[rustfmt::skip]
pub type FrameBody = signal_frame::ExchangeFrameBody<Input, Output>;
#[rustfmt::skip]
pub type Request = signal_frame::Request<Input>;
#[rustfmt::skip]
pub type ReplyEnvelope = signal_frame::Reply<Output>;
#[rustfmt::skip]
pub type RequestBuilder = signal_frame::RequestBuilder<Input>;
#[rustfmt::skip]
impl Input {
    pub fn into_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let request = signal_frame::Request::from_payload(self);
        Frame::with_short_header(
            short_header,
            FrameBody::Request {
                exchange,
                request,
            },
        )
    }
}
#[rustfmt::skip]
impl Output {
    pub fn into_reply_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let reply = signal_frame::Reply::committed(
            signal_frame::NonEmpty::single(signal_frame::SubReply::Ok(self)),
        );
        Frame::with_short_header(
            short_header,
            FrameBody::Reply {
                exchange,
                reply,
            },
        )
    }
}
