// @generated by schema-rust

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
pub use signal_lojix::schema::lib::DeploymentIdentifier as DeploymentIdentifier;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::GenerationIdentifier as GenerationIdentifier;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::TestRunIdentifier as TestRunIdentifier;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::ClusterName as ClusterName;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::NodeName as NodeName;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::UserName as UserName;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::PinLabel as PinLabel;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::HostComposition as HostComposition;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::HostDeployAction as HostDeployAction;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::UserEnvironmentAction as UserEnvironmentAction;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::SourceRevisionPolicy as SourceRevisionPolicy;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::GenerationSlot as GenerationSlot;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::ProposalSource as ProposalSource;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::FlakeReference as FlakeReference;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::DeploymentTransport as DeploymentTransport;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::DeploymentInputMode as DeploymentInputMode;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::DeploymentOutputSelector as DeploymentOutputSelector;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::ActivationBackend as ActivationBackend;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::NixBuilderSpec as NixBuilderSpec;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::TestExecutionProfile as TestExecutionProfile;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::DatabaseMarker as DatabaseMarker;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::DeploymentRecord as DeploymentRecord;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::TestMode as TestMode;
#[rustfmt::skip]
pub use signal_lojix::schema::lib::HostSelection as HostSelection;

#[rustfmt::skip]
#[cfg(feature = "dotos-text")]
pub use dotos::{DotosDecodeError, DotosEncode, DotosSource};

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeployPayload(DeployRequest);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PinPayload(PinRequest);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UnpinPayload(UnpinRequest);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RetirePayload(RetireRequest);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TestPayload(TestRequest);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeployAcceptedPayload(DeployHandle);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeployRejectedPayload(RejectedDeploy);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeployTerminalPayload(DeploymentRecord);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PinnedPayload(AppliedPin);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PinRejectedPayload(RejectedPin);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UnpinnedPayload(AppliedUnpin);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UnpinRejectedPayload(RejectedUnpin);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RetiredPayload(AppliedRetire);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RetireRejectedPayload(RejectedRetire);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TestedPayload(AcceptedTest);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TestRejectedPayload(RejectedTest);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum TestRequest {
    Run(TestRun),
    Check(QuickCheck),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NodeSelection {
    Nodes(Vec<NodeName>),
    All,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TestRun {
    pub cluster_name: ClusterName,
    pub node_selection: NodeSelection,
    pub host_selection: HostSelection,
    pub test_execution_profile: TestExecutionProfile,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct QuickCheck(Vec<NodeName>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ExtraSubstituter {
    pub url: String,
    pub public_key: String,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct HostDeployment {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub host_composition: HostComposition,
    pub proposal_source: ProposalSource,
    pub flake_reference: FlakeReference,
    pub deployment_transport: DeploymentTransport,
    pub deployment_input_mode: DeploymentInputMode,
    pub deployment_output_selector: DeploymentOutputSelector,
    pub activation_backend: ActivationBackend,
    pub host_deploy_action: HostDeployAction,
    pub source_revision_policy: SourceRevisionPolicy,
    pub optional_nix_builder_spec: Option<NixBuilderSpec>,
    pub extra_substituter_vector: Vec<ExtraSubstituter>,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UserEnvironmentDeployment {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub user_name: UserName,
    pub proposal_source: ProposalSource,
    pub flake_reference: FlakeReference,
    pub deployment_transport: DeploymentTransport,
    pub deployment_input_mode: DeploymentInputMode,
    pub deployment_output_selector: DeploymentOutputSelector,
    pub activation_backend: ActivationBackend,
    pub user_environment_action: UserEnvironmentAction,
    pub source_revision_policy: SourceRevisionPolicy,
    pub optional_nix_builder_spec: Option<NixBuilderSpec>,
    pub extra_substituter_vector: Vec<ExtraSubstituter>,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum DeployRequest {
    Host(HostDeployment),
    UserEnvironment(UserEnvironmentDeployment),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PinRequest {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub generation_identifier: GenerationIdentifier,
    pub pin_label: PinLabel,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UnpinRequest {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub pin_label: PinLabel,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RetireRequest {
    pub cluster_name: ClusterName,
    pub node_name: NodeName,
    pub generation_identifier: GenerationIdentifier,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeployHandle {
    pub deployment_identifier: DeploymentIdentifier,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AcceptedTest {
    pub test_run_identifier: TestRunIdentifier,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AppliedPin {
    pub generation_identifier: GenerationIdentifier,
    pub pin_label: PinLabel,
    pub from_slot: GenerationSlot,
    pub to_slot: GenerationSlot,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AppliedUnpin {
    pub generation_identifier: GenerationIdentifier,
    pub pin_label: PinLabel,
    pub from_slot: GenerationSlot,
    pub to_slot: GenerationSlot,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AppliedRetire {
    pub generation_identifier: GenerationIdentifier,
    pub generation_slot: GenerationSlot,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum PinRejectionReason {
    GenerationUnknown,
    NodeUnknown,
    PinLabelInUse,
    PinSlotExhausted,
    InternalError,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum UnpinRejectionReason {
    PinLabelUnknown,
    NodeUnknown,
    GenerationNotPinned,
    InternalError,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum RetireRejectionReason {
    GenerationUnknown,
    NodeUnknown,
    GenerationActive,
    GenerationPinned,
    InternalError,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum TestRejectionReason {
    ClusterUnknown,
    NodeUnknown,
    VmHostNotDeclaredForNode,
    HostDeclaresNoVmHost,
    NoTestDefaults,
    LiveNotYetEnabled,
    SubstrateUnavailable,
    InternalError,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectedDeploy(DeploymentRecord);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectedPin {
    pub pin_rejection_reason: PinRejectionReason,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectedUnpin {
    pub unpin_rejection_reason: UnpinRejectionReason,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectedRetire {
    pub retire_rejection_reason: RetireRejectionReason,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectedTest {
    pub test_rejection_reason: TestRejectionReason,
    pub database_marker: DatabaseMarker,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Deploy(DeployPayload),
    Pin(PinPayload),
    Unpin(UnpinPayload),
    Retire(RetirePayload),
    Test(TestPayload),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    DeployAccepted(DeployAcceptedPayload),
    DeployRejected(DeployRejectedPayload),
    DeployTerminal(DeployTerminalPayload),
    Pinned(PinnedPayload),
    PinRejected(PinRejectedPayload),
    Unpinned(UnpinnedPayload),
    UnpinRejected(UnpinRejectedPayload),
    Retired(RetiredPayload),
    RetireRejected(RetireRejectedPayload),
    Tested(TestedPayload),
    TestRejected(TestRejectedPayload),
}

#[rustfmt::skip]
impl DeployPayload {
    pub fn new(payload: DeployRequest) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &DeployRequest {
        &self.0
    }
    pub fn into_payload(self) -> DeployRequest {
        self.0
    }
}
#[rustfmt::skip]
impl From<DeployRequest> for DeployPayload {
    fn from(payload: DeployRequest) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PinPayload {
    pub fn new(payload: PinRequest) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &PinRequest {
        &self.0
    }
    pub fn into_payload(self) -> PinRequest {
        self.0
    }
}
#[rustfmt::skip]
impl From<PinRequest> for PinPayload {
    fn from(payload: PinRequest) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl UnpinPayload {
    pub fn new(payload: UnpinRequest) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &UnpinRequest {
        &self.0
    }
    pub fn into_payload(self) -> UnpinRequest {
        self.0
    }
}
#[rustfmt::skip]
impl From<UnpinRequest> for UnpinPayload {
    fn from(payload: UnpinRequest) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RetirePayload {
    pub fn new(payload: RetireRequest) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RetireRequest {
        &self.0
    }
    pub fn into_payload(self) -> RetireRequest {
        self.0
    }
}
#[rustfmt::skip]
impl From<RetireRequest> for RetirePayload {
    fn from(payload: RetireRequest) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TestPayload {
    pub fn new(payload: TestRequest) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &TestRequest {
        &self.0
    }
    pub fn into_payload(self) -> TestRequest {
        self.0
    }
}
#[rustfmt::skip]
impl From<TestRequest> for TestPayload {
    fn from(payload: TestRequest) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DeployAcceptedPayload {
    pub fn new(payload: DeployHandle) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &DeployHandle {
        &self.0
    }
    pub fn into_payload(self) -> DeployHandle {
        self.0
    }
}
#[rustfmt::skip]
impl From<DeployHandle> for DeployAcceptedPayload {
    fn from(payload: DeployHandle) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DeployRejectedPayload {
    pub fn new(payload: RejectedDeploy) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RejectedDeploy {
        &self.0
    }
    pub fn into_payload(self) -> RejectedDeploy {
        self.0
    }
}
#[rustfmt::skip]
impl From<RejectedDeploy> for DeployRejectedPayload {
    fn from(payload: RejectedDeploy) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DeployTerminalPayload {
    pub fn new(payload: DeploymentRecord) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &DeploymentRecord {
        &self.0
    }
    pub fn into_payload(self) -> DeploymentRecord {
        self.0
    }
}
#[rustfmt::skip]
impl From<DeploymentRecord> for DeployTerminalPayload {
    fn from(payload: DeploymentRecord) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PinnedPayload {
    pub fn new(payload: AppliedPin) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &AppliedPin {
        &self.0
    }
    pub fn into_payload(self) -> AppliedPin {
        self.0
    }
}
#[rustfmt::skip]
impl From<AppliedPin> for PinnedPayload {
    fn from(payload: AppliedPin) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PinRejectedPayload {
    pub fn new(payload: RejectedPin) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RejectedPin {
        &self.0
    }
    pub fn into_payload(self) -> RejectedPin {
        self.0
    }
}
#[rustfmt::skip]
impl From<RejectedPin> for PinRejectedPayload {
    fn from(payload: RejectedPin) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl UnpinnedPayload {
    pub fn new(payload: AppliedUnpin) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &AppliedUnpin {
        &self.0
    }
    pub fn into_payload(self) -> AppliedUnpin {
        self.0
    }
}
#[rustfmt::skip]
impl From<AppliedUnpin> for UnpinnedPayload {
    fn from(payload: AppliedUnpin) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl UnpinRejectedPayload {
    pub fn new(payload: RejectedUnpin) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RejectedUnpin {
        &self.0
    }
    pub fn into_payload(self) -> RejectedUnpin {
        self.0
    }
}
#[rustfmt::skip]
impl From<RejectedUnpin> for UnpinRejectedPayload {
    fn from(payload: RejectedUnpin) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RetiredPayload {
    pub fn new(payload: AppliedRetire) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &AppliedRetire {
        &self.0
    }
    pub fn into_payload(self) -> AppliedRetire {
        self.0
    }
}
#[rustfmt::skip]
impl From<AppliedRetire> for RetiredPayload {
    fn from(payload: AppliedRetire) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RetireRejectedPayload {
    pub fn new(payload: RejectedRetire) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RejectedRetire {
        &self.0
    }
    pub fn into_payload(self) -> RejectedRetire {
        self.0
    }
}
#[rustfmt::skip]
impl From<RejectedRetire> for RetireRejectedPayload {
    fn from(payload: RejectedRetire) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TestedPayload {
    pub fn new(payload: AcceptedTest) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &AcceptedTest {
        &self.0
    }
    pub fn into_payload(self) -> AcceptedTest {
        self.0
    }
}
#[rustfmt::skip]
impl From<AcceptedTest> for TestedPayload {
    fn from(payload: AcceptedTest) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TestRejectedPayload {
    pub fn new(payload: RejectedTest) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RejectedTest {
        &self.0
    }
    pub fn into_payload(self) -> RejectedTest {
        self.0
    }
}
#[rustfmt::skip]
impl From<RejectedTest> for TestRejectedPayload {
    fn from(payload: RejectedTest) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl QuickCheck {
    pub fn new(payload: Vec<NodeName>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<NodeName> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<NodeName> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<NodeName>> for QuickCheck {
    fn from(payload: Vec<NodeName>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RejectedDeploy {
    pub fn new(payload: DeploymentRecord) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &DeploymentRecord {
        &self.0
    }
    pub fn into_payload(self) -> DeploymentRecord {
        self.0
    }
}
#[rustfmt::skip]
impl From<DeploymentRecord> for RejectedDeploy {
    fn from(payload: DeploymentRecord) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TestRequest {
    pub fn run(payload: TestRun) -> Self {
        Self::Run(payload)
    }
    pub fn check(payload: Vec<NodeName>) -> Self {
        Self::Check(QuickCheck::new(payload))
    }
}

#[rustfmt::skip]
impl NodeSelection {
    pub fn nodes(payload: Vec<NodeName>) -> Self {
        Self::Nodes(payload)
    }
}

#[rustfmt::skip]
impl DeployRequest {
    pub fn host(payload: HostDeployment) -> Self {
        Self::Host(payload)
    }
    pub fn user_environment(payload: UserEnvironmentDeployment) -> Self {
        Self::UserEnvironment(payload)
    }
}

#[rustfmt::skip]
impl Input {
    pub fn deploy(payload: DeployRequest) -> Self {
        Self::Deploy(DeployPayload::new(payload))
    }
    pub fn pin(payload: PinRequest) -> Self {
        Self::Pin(PinPayload::new(payload))
    }
    pub fn unpin(payload: UnpinRequest) -> Self {
        Self::Unpin(UnpinPayload::new(payload))
    }
    pub fn retire(payload: RetireRequest) -> Self {
        Self::Retire(RetirePayload::new(payload))
    }
    pub fn test(payload: TestRequest) -> Self {
        Self::Test(TestPayload::new(payload))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn deploy_accepted(payload: DeployHandle) -> Self {
        Self::DeployAccepted(DeployAcceptedPayload::new(payload))
    }
    pub fn deploy_rejected(payload: RejectedDeploy) -> Self {
        Self::DeployRejected(DeployRejectedPayload::new(payload))
    }
    pub fn deploy_terminal(payload: DeploymentRecord) -> Self {
        Self::DeployTerminal(DeployTerminalPayload::new(payload))
    }
    pub fn pinned(payload: AppliedPin) -> Self {
        Self::Pinned(PinnedPayload::new(payload))
    }
    pub fn pin_rejected(payload: RejectedPin) -> Self {
        Self::PinRejected(PinRejectedPayload::new(payload))
    }
    pub fn unpinned(payload: AppliedUnpin) -> Self {
        Self::Unpinned(UnpinnedPayload::new(payload))
    }
    pub fn unpin_rejected(payload: RejectedUnpin) -> Self {
        Self::UnpinRejected(UnpinRejectedPayload::new(payload))
    }
    pub fn retired(payload: AppliedRetire) -> Self {
        Self::Retired(RetiredPayload::new(payload))
    }
    pub fn retire_rejected(payload: RejectedRetire) -> Self {
        Self::RetireRejected(RetireRejectedPayload::new(payload))
    }
    pub fn tested(payload: AcceptedTest) -> Self {
        Self::Tested(TestedPayload::new(payload))
    }
    pub fn test_rejected(payload: RejectedTest) -> Self {
        Self::TestRejected(TestRejectedPayload::new(payload))
    }
}

#[rustfmt::skip]
impl From<TestRun> for TestRequest {
    fn from(payload: TestRun) -> Self {
        Self::Run(payload)
    }
}

#[rustfmt::skip]
impl From<QuickCheck> for TestRequest {
    fn from(payload: QuickCheck) -> Self {
        Self::Check(payload)
    }
}

#[rustfmt::skip]
impl From<HostDeployment> for DeployRequest {
    fn from(payload: HostDeployment) -> Self {
        Self::Host(payload)
    }
}

#[rustfmt::skip]
impl From<UserEnvironmentDeployment> for DeployRequest {
    fn from(payload: UserEnvironmentDeployment) -> Self {
        Self::UserEnvironment(payload)
    }
}

#[rustfmt::skip]
impl From<DeployPayload> for Input {
    fn from(payload: DeployPayload) -> Self {
        Self::Deploy(payload)
    }
}

#[rustfmt::skip]
impl From<PinPayload> for Input {
    fn from(payload: PinPayload) -> Self {
        Self::Pin(payload)
    }
}

#[rustfmt::skip]
impl From<UnpinPayload> for Input {
    fn from(payload: UnpinPayload) -> Self {
        Self::Unpin(payload)
    }
}

#[rustfmt::skip]
impl From<RetirePayload> for Input {
    fn from(payload: RetirePayload) -> Self {
        Self::Retire(payload)
    }
}

#[rustfmt::skip]
impl From<TestPayload> for Input {
    fn from(payload: TestPayload) -> Self {
        Self::Test(payload)
    }
}

#[rustfmt::skip]
impl From<DeployAcceptedPayload> for Output {
    fn from(payload: DeployAcceptedPayload) -> Self {
        Self::DeployAccepted(payload)
    }
}

#[rustfmt::skip]
impl From<DeployRejectedPayload> for Output {
    fn from(payload: DeployRejectedPayload) -> Self {
        Self::DeployRejected(payload)
    }
}

#[rustfmt::skip]
impl From<DeployTerminalPayload> for Output {
    fn from(payload: DeployTerminalPayload) -> Self {
        Self::DeployTerminal(payload)
    }
}

#[rustfmt::skip]
impl From<PinnedPayload> for Output {
    fn from(payload: PinnedPayload) -> Self {
        Self::Pinned(payload)
    }
}

#[rustfmt::skip]
impl From<PinRejectedPayload> for Output {
    fn from(payload: PinRejectedPayload) -> Self {
        Self::PinRejected(payload)
    }
}

#[rustfmt::skip]
impl From<UnpinnedPayload> for Output {
    fn from(payload: UnpinnedPayload) -> Self {
        Self::Unpinned(payload)
    }
}

#[rustfmt::skip]
impl From<UnpinRejectedPayload> for Output {
    fn from(payload: UnpinRejectedPayload) -> Self {
        Self::UnpinRejected(payload)
    }
}

#[rustfmt::skip]
impl From<RetiredPayload> for Output {
    fn from(payload: RetiredPayload) -> Self {
        Self::Retired(payload)
    }
}

#[rustfmt::skip]
impl From<RetireRejectedPayload> for Output {
    fn from(payload: RetireRejectedPayload) -> Self {
        Self::RetireRejected(payload)
    }
}

#[rustfmt::skip]
impl From<TestedPayload> for Output {
    fn from(payload: TestedPayload) -> Self {
        Self::Tested(payload)
    }
}

#[rustfmt::skip]
impl From<TestRejectedPayload> for Output {
    fn from(payload: TestRejectedPayload) -> Self {
        Self::TestRejected(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "dotos-text")]
impl std::str::FromStr for Input {
    type Err = DotosDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        DotosSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "dotos-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as DotosEncode>::to_dotos(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "dotos-text")]
impl std::str::FromStr for Output {
    type Err = DotosDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        DotosSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "dotos-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as DotosEncode>::to_dotos(self))
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_DEPLOY: u64 = 0x0000000100000006;
    pub const INPUT_PIN: u64 = 0x0001000100000006;
    pub const INPUT_UNPIN: u64 = 0x0002000100000006;
    pub const INPUT_RETIRE: u64 = 0x0003000100000006;
    pub const INPUT_TEST: u64 = 0x0004000100000006;
    pub const OUTPUT_DEPLOY_ACCEPTED: u64 = 0x0100000100000006;
    pub const OUTPUT_DEPLOY_REJECTED: u64 = 0x0101000100000006;
    pub const OUTPUT_DEPLOY_TERMINAL: u64 = 0x0102000100000006;
    pub const OUTPUT_PINNED: u64 = 0x0103000100000006;
    pub const OUTPUT_PIN_REJECTED: u64 = 0x0104000100000006;
    pub const OUTPUT_UNPINNED: u64 = 0x0105000100000006;
    pub const OUTPUT_UNPIN_REJECTED: u64 = 0x0106000100000006;
    pub const OUTPUT_RETIRED: u64 = 0x0107000100000006;
    pub const OUTPUT_RETIRE_REJECTED: u64 = 0x0108000100000006;
    pub const OUTPUT_TESTED: u64 = 0x0109000100000006;
    pub const OUTPUT_TEST_REJECTED: u64 = 0x010A000100000006;
    pub const HANDSHAKE_REQUEST: u64 = 0xFF00000100000006;
    pub const HANDSHAKE_REPLY: u64 = 0xFF01000100000006;
    pub const ENGINE_REFUSAL: u64 = 0xFF02000100000006;
}

#[rustfmt::skip]
pub enum ContractMarker {}
#[rustfmt::skip]
impl signal_frame::WireContract for ContractMarker {
    const BINDING: signal_frame::ContractBinding = signal_frame::ContractBinding::new(
        match signal_frame::ContractId::try_new(6u32) {
            Ok(contract) => contract,
            Err(_) => panic!("generated contract ID must be nonzero"),
        },
        match signal_frame::WireRevision::try_new(1u16) {
            Ok(revision) => revision,
            Err(_) => panic!("generated wire revision must be nonzero"),
        },
    );
}
#[rustfmt::skip]
/// Why the daemon refused to produce an ordinary reply.
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq
)]
pub enum EngineRefusalReason {
    /// The engine ran and rejected the request with its typed
    /// domain error; the rendered error text is the detail.
    Rejected,
    /// The engine layer could not serve the request at all.
    Unavailable,
}
#[rustfmt::skip]
impl std::fmt::Display for EngineRefusalReason {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Rejected => formatter.write_str("engine rejected the request"),
            Self::Unavailable => formatter.write_str("engine unavailable"),
        }
    }
}
#[rustfmt::skip]
/// The refusal reply a daemon writes when the engine failed, so
/// the caller receives a complete typed frame instead of a closed
/// socket it cannot distinguish from daemon death. The typed
/// engine error stays daemon-side; the wire carries the
/// classification plus the rendered error text.
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EngineRefusal {
    pub reason: EngineRefusalReason,
    pub detail: String,
}
#[rustfmt::skip]
impl EngineRefusal {
    pub fn rejected(detail: String) -> Self {
        Self {
            reason: EngineRefusalReason::Rejected,
            detail,
        }
    }
    pub fn unavailable(detail: String) -> Self {
        Self {
            reason: EngineRefusalReason::Unavailable,
            detail,
        }
    }
    pub fn encode_bound_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            signal_frame::SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&short_header::ENGINE_REFUSAL.to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
}
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    FrameEncode,
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    LegacyHeader { contract_id: u32, wire_revision: u16 },
    ContractMismatch { expected: u32, found: u32 },
    UnsupportedWireRevision { contract_id: u32, expected: u16, found: u16 },
    UnknownRoute { root: u8, variant: u8 },
    RouteBodyMismatch { root: u8, variant: u8, body: &'static str },
    UnexpectedFrameBody { found: &'static str },
    OperationCount { found: usize },
    EngineRefused { refusal: EngineRefusal },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::FrameEncode => {
                formatter.write_str("failed to encode bound signal frame")
            }
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::LegacyHeader { contract_id, wire_revision } => {
                write!(
                    formatter,
                    "legacy unbound signal frame ({contract_id}, {wire_revision})"
                )
            }
            Self::ContractMismatch { expected, found } => {
                write!(
                    formatter,
                    "signal contract mismatch: expected {expected}, found {found}"
                )
            }
            Self::UnsupportedWireRevision { contract_id, expected, found } => {
                write!(
                    formatter,
                    "unsupported wire revision for contract {contract_id}: expected {expected}, found {found}"
                )
            }
            Self::UnknownRoute { root, variant } => {
                write!(formatter, "unknown bound signal route ({root}, {variant})")
            }
            Self::RouteBodyMismatch { root, variant, body } => {
                write!(
                    formatter,
                    "bound signal route ({root}, {variant}) does not carry {body}"
                )
            }
            Self::UnexpectedFrameBody { found } => {
                write!(formatter, "expected one request frame, found {found}")
            }
            Self::OperationCount { found } => {
                write!(formatter, "expected one request operation, found {found}")
            }
            Self::EngineRefused { refusal } => {
                write!(formatter, "{}: {}", refusal.reason, refusal.detail)
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}
#[rustfmt::skip]
impl ContractMarker {
    pub fn handshake_request_frame(request: signal_frame::HandshakeRequest) -> Frame {
        Frame::new(
            signal_frame::WireRoute::new(
                signal_frame::RootCode::new(0xff),
                signal_frame::VariantCode::new(0),
            ),
            FrameBody::HandshakeRequest(request),
        )
    }
    pub fn handshake_reply_frame(reply: signal_frame::HandshakeReply) -> Frame {
        Frame::new(
            signal_frame::WireRoute::new(
                signal_frame::RootCode::new(0xff),
                signal_frame::VariantCode::new(1),
            ),
            FrameBody::HandshakeReply(reply),
        )
    }
    pub fn decode_frame(bytes: &[u8]) -> Result<Frame, SignalFrameError> {
        if bytes.len() < signal_frame::SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: bytes.len(),
            });
        }
        let mut header_bytes = [0_u8; signal_frame::SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&bytes[..signal_frame::SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let contract_id = header as u32;
        let wire_revision = (header >> 32) as u16;
        if contract_id == 0 || wire_revision == 0 {
            return Err(SignalFrameError::LegacyHeader {
                contract_id,
                wire_revision,
            });
        }
        if contract_id != 6u32 {
            return Err(SignalFrameError::ContractMismatch {
                expected: 6u32,
                found: contract_id,
            });
        }
        if wire_revision != 1u16 {
            return Err(SignalFrameError::UnsupportedWireRevision {
                contract_id,
                expected: 1u16,
                found: wire_revision,
            });
        }
        let root = (header >> 56) as u8;
        let variant = (header >> 48) as u8;
        match (root, variant) {
            (0, 0)
            | (0, 1)
            | (0, 2)
            | (0, 3)
            | (0, 4)
            | (1, 0)
            | (1, 1)
            | (1, 2)
            | (1, 3)
            | (1, 4)
            | (1, 5)
            | (1, 6)
            | (1, 7)
            | (1, 8)
            | (1, 9)
            | (1, 10)
            | (0xff, 0)
            | (0xff, 1)
            | (0xff, 2) => {}
            _ => {
                return Err(SignalFrameError::UnknownRoute {
                    root,
                    variant,
                });
            }
        }
        if (root, variant) == (0xff, 2) {
            let refusal = rkyv::from_bytes::<
                EngineRefusal,
                rkyv::rancor::Error,
            >(&bytes[signal_frame::SHORT_HEADER_BYTE_COUNT..])
                .map_err(|_| SignalFrameError::ArchiveDecode)?;
            return Err(SignalFrameError::EngineRefused {
                refusal,
            });
        }
        let frame = Frame::decode(bytes).map_err(|_| SignalFrameError::ArchiveDecode)?;
        let header_route = signal_frame::WireRoute::new(
            signal_frame::RootCode::new(root),
            signal_frame::VariantCode::new(variant),
        );
        let body_matches = match frame.body() {
            FrameBody::HandshakeRequest(_) => (root, variant) == (0xff, 0),
            FrameBody::HandshakeReply(_) => (root, variant) == (0xff, 1),
            FrameBody::Request { request, .. } => {
                request.route().is_ok_and(|route| route == header_route)
            }
            FrameBody::Reply { reply, .. } => {
                match reply {
                    signal_frame::Reply::Accepted { per_operation, .. } => {
                        match per_operation.head() {
                            signal_frame::SubReply::Ok(output) => {
                                output.wire_route() == header_route
                            }
                            signal_frame::SubReply::Failed {
                                detail: Some(output),
                                ..
                            } => output.wire_route() == header_route,
                            signal_frame::SubReply::Invalidated
                            | signal_frame::SubReply::Failed { detail: None, .. }
                            | signal_frame::SubReply::Skipped => root == 1,
                        }
                    }
                    signal_frame::Reply::Rejected { .. } => root == 1,
                }
            }
        };
        if !body_matches {
            let body = match frame.body() {
                FrameBody::HandshakeRequest(_) => "handshake request",
                FrameBody::HandshakeReply(_) => "handshake reply",
                FrameBody::Request { .. } => "request",
                FrameBody::Reply { .. } => "reply",
            };
            return Err(SignalFrameError::RouteBodyMismatch {
                root,
                variant,
                body,
            });
        }
        Ok(frame)
    }
    pub fn decode_single_request(
        bytes: &[u8],
    ) -> Result<(signal_frame::ExchangeIdentifier, Input), SignalFrameError> {
        let frame = Self::decode_frame(bytes)?;
        match frame.into_body() {
            FrameBody::Request { exchange, request } => {
                let found = request.payloads().len();
                if found != 1 {
                    return Err(SignalFrameError::OperationCount {
                        found,
                    });
                }
                Ok((exchange, request.payloads.into_head()))
            }
            FrameBody::HandshakeRequest(_) => {
                Err(SignalFrameError::UnexpectedFrameBody {
                    found: "handshake request",
                })
            }
            FrameBody::HandshakeReply(_) => {
                Err(SignalFrameError::UnexpectedFrameBody {
                    found: "handshake reply",
                })
            }
            FrameBody::Reply { .. } => {
                Err(SignalFrameError::UnexpectedFrameBody {
                    found: "reply",
                })
            }
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    Deploy,
    Pin,
    Unpin,
    Retire,
    Test,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    DeployAccepted,
    DeployRejected,
    DeployTerminal,
    Pinned,
    PinRejected,
    Unpinned,
    UnpinRejected,
    Retired,
    RetireRejected,
    Tested,
    TestRejected,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Deploy(_) => InputRoute::Deploy,
            Self::Pin(_) => InputRoute::Pin,
            Self::Unpin(_) => InputRoute::Unpin,
            Self::Retire(_) => InputRoute::Retire,
            Self::Test(_) => InputRoute::Test,
        }
    }
    pub fn wire_route(&self) -> signal_frame::WireRoute {
        match self {
            Self::Deploy(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(0),
                    signal_frame::VariantCode::new(0),
                )
            }
            Self::Pin(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(0),
                    signal_frame::VariantCode::new(1),
                )
            }
            Self::Unpin(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(0),
                    signal_frame::VariantCode::new(2),
                )
            }
            Self::Retire(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(0),
                    signal_frame::VariantCode::new(3),
                )
            }
            Self::Test(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(0),
                    signal_frame::VariantCode::new(4),
                )
            }
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Deploy(_) => short_header::INPUT_DEPLOY,
            Self::Pin(_) => short_header::INPUT_PIN,
            Self::Unpin(_) => short_header::INPUT_UNPIN,
            Self::Retire(_) => short_header::INPUT_RETIRE,
            Self::Test(_) => short_header::INPUT_TEST,
        }
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::DeployAccepted(_) => OutputRoute::DeployAccepted,
            Self::DeployRejected(_) => OutputRoute::DeployRejected,
            Self::DeployTerminal(_) => OutputRoute::DeployTerminal,
            Self::Pinned(_) => OutputRoute::Pinned,
            Self::PinRejected(_) => OutputRoute::PinRejected,
            Self::Unpinned(_) => OutputRoute::Unpinned,
            Self::UnpinRejected(_) => OutputRoute::UnpinRejected,
            Self::Retired(_) => OutputRoute::Retired,
            Self::RetireRejected(_) => OutputRoute::RetireRejected,
            Self::Tested(_) => OutputRoute::Tested,
            Self::TestRejected(_) => OutputRoute::TestRejected,
        }
    }
    pub fn wire_route(&self) -> signal_frame::WireRoute {
        match self {
            Self::DeployAccepted(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(0),
                )
            }
            Self::DeployRejected(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(1),
                )
            }
            Self::DeployTerminal(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(2),
                )
            }
            Self::Pinned(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(3),
                )
            }
            Self::PinRejected(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(4),
                )
            }
            Self::Unpinned(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(5),
                )
            }
            Self::UnpinRejected(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(6),
                )
            }
            Self::Retired(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(7),
                )
            }
            Self::RetireRejected(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(8),
                )
            }
            Self::Tested(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(9),
                )
            }
            Self::TestRejected(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(10),
                )
            }
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::DeployAccepted(_) => short_header::OUTPUT_DEPLOY_ACCEPTED,
            Self::DeployRejected(_) => short_header::OUTPUT_DEPLOY_REJECTED,
            Self::DeployTerminal(_) => short_header::OUTPUT_DEPLOY_TERMINAL,
            Self::Pinned(_) => short_header::OUTPUT_PINNED,
            Self::PinRejected(_) => short_header::OUTPUT_PIN_REJECTED,
            Self::Unpinned(_) => short_header::OUTPUT_UNPINNED,
            Self::UnpinRejected(_) => short_header::OUTPUT_UNPIN_REJECTED,
            Self::Retired(_) => short_header::OUTPUT_RETIRED,
            Self::RetireRejected(_) => short_header::OUTPUT_RETIRE_REJECTED,
            Self::Tested(_) => short_header::OUTPUT_TESTED,
            Self::TestRejected(_) => short_header::OUTPUT_TEST_REJECTED,
        }
    }
}

#[rustfmt::skip]
impl signal_frame::RequestPayload for Input {}
#[rustfmt::skip]
impl signal_frame::SignalOperationHeads for Input {
    const HEADS: &'static [&'static str] = &["Deploy", "Pin", "Unpin", "Retire", "Test"];
}
#[rustfmt::skip]
impl signal_frame::LogVariant for Input {
    fn log_variant(&self) -> u64 {
        let route = self.wire_route();
        u64::from(route.root().value()) | (u64::from(route.variant().value()) << 8)
    }
}
#[rustfmt::skip]
pub type Frame = signal_frame::BoundExchangeFrame<ContractMarker, Input, Output>;
#[rustfmt::skip]
pub type FrameBody = signal_frame::ExchangeFrameBody<Input, Output>;
#[rustfmt::skip]
pub type Request = signal_frame::Request<Input>;
#[rustfmt::skip]
pub type ReplyEnvelope = signal_frame::Reply<Output>;
#[rustfmt::skip]
pub type RequestBuilder = signal_frame::RequestBuilder<Input>;
#[rustfmt::skip]
impl Input {
    pub fn into_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let route = self.wire_route();
        let request = signal_frame::Request::from_payload(self);
        Frame::new(
            route,
            FrameBody::Request {
                exchange,
                request,
            },
        )
    }
    pub fn encode_request_frame(
        self,
        exchange: signal_frame::ExchangeIdentifier,
    ) -> Result<Vec<u8>, SignalFrameError> {
        self.into_frame(exchange).encode().map_err(|_| SignalFrameError::FrameEncode)
    }
}
#[rustfmt::skip]
impl Output {
    pub fn into_reply_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let route = self.wire_route();
        let reply = signal_frame::Reply::committed(
            signal_frame::NonEmpty::single(signal_frame::SubReply::Ok(self)),
        );
        Frame::new(
            route,
            FrameBody::Reply {
                exchange,
                reply,
            },
        )
    }
    pub fn encode_reply_frame(
        self,
        exchange: signal_frame::ExchangeIdentifier,
    ) -> Result<Vec<u8>, SignalFrameError> {
        self.into_reply_frame(exchange)
            .encode()
            .map_err(|_| SignalFrameError::FrameEncode)
    }
}
